name: Show SHA Values

on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  show-shas:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: jwalton/gh-find-current-pr@master
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}
          
      - name: Get Pull Request Number
        id: pr
        run: |
          echo "pull_request_number=$(gh pr view --json number -q .number || echo '')" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Display Values
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "PR Number (from gh cli): ${{ steps.pr.outputs.pull_request_number }}"
          echo "AAA": ${{ github.event.pull_request.number }}
          echo "github.event.number: ${{ github.event.number }}"
          echo "GitHub SHA: ${{ github.sha }}"
          
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            if [ "${{ github.event.pull_request.head.sha }}" != "${{ github.sha }}" ]; then
              echo "Note: The SHAs are different!"
            else
              echo "The SHAs are identical"
            fi
          fi

          